name: .NET 8 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore EmployeeMgmt_API.csproj

      - name: Build
        run: dotnet build EmployeeMgmt_API.csproj --no-restore --configuration Release

      - name: Publish
        run: dotnet publish EmployeeMgmt_API.csproj -c Release -o ./publish

      - name: Test
        run: dotnet test EmployeeMgmt_API.csproj --no-build --configuration Release
